package geektime.spring.springbucks.pojo;

import lombok.Data;

import java.io.Serializable;

@Data
public class OrderCoffee implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER_COFFEE.COFFEE_ORDER_ID
     *
     * @mbg.generated Thu Jun 02 00:34:22 CST 2022
     */
    private Long coffeeOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER_COFFEE.ITEMS_ID
     *
     * @mbg.generated Thu Jun 02 00:34:22 CST 2022
     */
    private Long itemsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_ORDER_COFFEE
     *
     * @mbg.generated Thu Jun 02 00:34:22 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER_COFFEE.COFFEE_ORDER_ID
     *
     * @return the value of T_ORDER_COFFEE.COFFEE_ORDER_ID
     *
     * @mbg.generated Thu Jun 02 00:34:22 CST 2022
     */
    public Long getCoffeeOrderId() {
        return coffeeOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ORDER_COFFEE
     *
     * @mbg.generated Thu Jun 02 00:34:22 CST 2022
     */
    public OrderCoffee withCoffeeOrderId(Long coffeeOrderId) {
        this.setCoffeeOrderId(coffeeOrderId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER_COFFEE.COFFEE_ORDER_ID
     *
     * @param coffeeOrderId the value for T_ORDER_COFFEE.COFFEE_ORDER_ID
     *
     * @mbg.generated Thu Jun 02 00:34:22 CST 2022
     */
    public void setCoffeeOrderId(Long coffeeOrderId) {
        this.coffeeOrderId = coffeeOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER_COFFEE.ITEMS_ID
     *
     * @return the value of T_ORDER_COFFEE.ITEMS_ID
     *
     * @mbg.generated Thu Jun 02 00:34:22 CST 2022
     */
    public Long getItemsId() {
        return itemsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ORDER_COFFEE
     *
     * @mbg.generated Thu Jun 02 00:34:22 CST 2022
     */
    public OrderCoffee withItemsId(Long itemsId) {
        this.setItemsId(itemsId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER_COFFEE.ITEMS_ID
     *
     * @param itemsId the value for T_ORDER_COFFEE.ITEMS_ID
     *
     * @mbg.generated Thu Jun 02 00:34:22 CST 2022
     */
    public void setItemsId(Long itemsId) {
        this.itemsId = itemsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ORDER_COFFEE
     *
     * @mbg.generated Thu Jun 02 00:34:22 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", coffeeOrderId=").append(coffeeOrderId);
        sb.append(", itemsId=").append(itemsId);
        sb.append("]");
        return sb.toString();
    }
}